### ISSUE TITLE
Bring back the README

### ISSUE THREAD

**Issue by bartfeenstra** [rabbitmq/rabbitmq-priority-queue#7]
The pain project page now contains a message saying RabbitMQ 3.5 will contain the priority queue. However, as there doesn't even seem to be a beta of 3.5, this message is very confusing. Maybe it's better if the code and documentation for 3.4.x are shown instead, with a small message mentioning 3.5.

**Comment by simonmacmullen** [comment]
The current README contains a link to the old README with documentation for 3.4.x.

And 3.5.0 is really imminent.

**Comment by bartfeenstra** [comment]
I know it does, but it surely makes the project look dead and unmaintained.

The only mention of 3.5.0 I have found was in this repository, and even it if is indeed imminent, enough people won't be able to upgrade to it immediately.

**Comment by videlalvaro** [comment]
>I know it does, but it surely makes the project look dead and unmaintained.

Well, this particular Github repo will be unmaintained once 3.5.0 is out. 

Isn't the following not clear enough for current users?

>For users of RabbitMQ 3.4.x or earlier, you can read the old version of the README at:
>https://github.com/rabbitmq/rabbitmq-priority-queue/tree/3431dc1ef8ea53e9a556c6be8bc1b417ac03b58d

**Comment by michaelklishin** [comment]
The project is about to become largely unmaintained, since `3.5.0` ships any day now.
